#### Tables ####

# START sourced from http://dnd5e.wikidot.com/
races = {
    "Common": [
        "Dragonborn", 
        "Dwarf", 
        "Elf", 
        "Gnome", 
        "Half-Elf", 
        "Half-Orc", 
        "Halfling", 
        "Human", 
        "Tiefling" 
    ],
    "Exotic": [
        "Aarakocra", 
        "Aasimar", 
        "Fairy", 
        "Firbolg", 
        "Genasi", 
        "Gith", 
        "Goliath", 
        "Harengon", 
        "Kenku", 
        "Locathah", 
        "Owlin", 
        "Tabaxi", 
        "Tortle", 
        "Triton", 
        "Verdan"
    ],
    "Monstrous": [
        "Bugbear", 
        "Centaur", 
        "Goblin", 
        "Grung", 
        "Hobgoblin", 
        "Kobold", 
        "Lizardfolk", 
        "Minotaur", 
        "Orc", 
        "Yuan-Ti Pureblood"
    ],
    "Eberron": [
        "Changeling", 
        "Kalashtar", 
        "Shifter", 
        "Warforged"
    ],
    "Planeshift": [
        "Aetherborn", 
        "Aven", 
        "Khenra", 
        "Kor", 
        "Merfolk", 
        "Naga", 
        "Siren", 
        "Vampire"
    ],
    "Ravenloft": [
        "Dhamphir", 
        "Hexblood", 
        "Reborn"
    ],
    "Ravnica": [
        "Loxodon", 
        "Simic Hybrid", 
        "Vedalken"
    ],
    "Theros": [
        "Leonin", 
        "Satyr"
    ]
}
classes = [
    "Artificer", 
    "Barbarian", 
    "Bard", 
    "Cleric", 
    "Druid", 
    "Fighter", 
    "Monk", 
    "Paladin", 
    "Ranger", 
    "Rogue", 
    "Sorcerer", 
    "Warlock", 
    "Wizard"
]
backgrounds = [
    "Acolyte", 
    "Anthropologist", 
    "Archaeologist", 
    "Athlete", 
    "Charlatan", 
    "City Watch", 
    "Clan Crafter", 
    "Cloistered Scholar", 
    "Courtier", 
    "Criminal", 
    "Entertainer", 
    "Faceless", 
    "Faction Agent", 
    "Far Traveler", 
    "Feylost", 
    "Fisher", 
    "Folk Hero", 
    "Gladiator", 
    "Guild Artisan", 
    "Guild Merchant", 
    "Haunted One", 
    "Hermit", 
    "House Agent", 
    "Inheritor", 
    "Investigator (SCAG)", 
    "Investigator (VRGR)", 
    "Knight", 
    "Knight of the Order", 
    "Marine", 
    "Mercenary Veteran", 
    "Noble", 
    "Outlander", 
    "Pirate", 
    "Sage", 
    "Sailor", 
    "Shipwright", 
    "Smuggler", 
    "Soldier", 
    "Spy", 
    "Urban Bounty Hunter", 
    "Urchin", 
    "Uthgardt Tribe Member", 
    "Waterdhavian Noble", 
    "Witchlight Hand", 
    "Black Fist Double Agent", 
    "Dragon Casualty", 
    "Iron Route Bandit", 
    "Phlan Insurgent", 
    "Stojanow Prisoner", 
    "Ticklebelly Nomad", 
    "Caravan Specialist", 
    "Earthspur Miner", 
    "Harborfolk", 
    "Mulmaster Aristocrat", 
    "Phlan Refugee", 
    "Cormanthor Refugee", 
    "Gate Urchin", 
    "Hillsfar Merchant", 
    "Hillsfar Smuggler", 
    "Secret Identity", 
    "Shade Fanatic", 
    "Trade Sheriff", 
]
# END sourced from http://dnd5e.wikidot.com/

# START posted on reddit by u/RamonDozol #### https://www.reddit.com/r/DnD5e/comments/mc5r2v/table_of_personality_traits/
personality_traits = [
    "I idolize a particular hero of my faith and constantly refer to that person's deeds and example.", 
    "I can find common ground between the fiercest enemies, empathizing with them and always working toward peace.", 
    "I see omens in every event and action. The gods try to speak to us, we just need to listen.", 
    "Nothing can shake my optimistic attitude.", 
    "I quote (or misquote) the sacred texts and proverbs in almost every situation.", 
    "I am tolerant (or intolerant) of other faiths and respect (or condemn) the worship of other gods.", 
    "I've enjoyed fine food, drink, and high society among my temple's elite. Rough living grates on me.", 
    "I've spent so long in the temple that I have little practical experience dealing with people in the outside world.", 
    "I fall in and out of love easily, and am always pursuing someone.", 
    "I have a joke for every occasion, especially occasions where humor is inappropriate.", 
    "Flattery is my preferred trick for getting what I want.", 
    "I'm a born gambler who can't resist taking a risk for a potential payoff.", 
    "I lie about almost everything, even when there's no good reason to.", 
    "Sarcasm and insults are my weapons of choice.", 
    "I keep multiple holy symbols on me and invoke whatever deity might come in useful at any given moment.", 
    "I pocket anything I see that might have some value.", 
    "I always have plan for what to do when things go wrong.", 
    "I am always calm, no matter what the situation. I never raise my voice or let my emotions control me.", 
    "The first thing I do in a new place is note the locations of everything valuable--or where such things could be hidden.", 
    "I would rather make a new friend than a new enemy.", 
    "I am incredibly slow to trust. Those who seem the fairest often have the most to hide.", 
    "I don't pay attention to the risks in a situation. Never tell me the odds.", 
    "The best way to get me to do something is to tell me I can't do it.", 
    "I blow up at the slightest insult.", 
    "I know a story relevant to almost every situation.", 
    "Whenever I come to a new place, I collect local rumors and spread gossip.", 
    "I'm a hopeless romantic, always searching for that 'special someone'.", 
    "Nobody stays angry at me or around me for long, since I can defuse any amount of tension.", 
    "I love a good insult, even one directed at me.", 
    "I get bitter if I'm not the center of attention.", 
    "I'll settle for nothing less than perfection.", 
    "I change my mood or my mind as quickly as I change key in a song.", 
    "I judge people by their actions, not their words.", 
    "If someone is in trouble, I'm always willing to lend help.", 
    "When I set my mind to something, I follow through no matter what gets in my way.", 
    "I have a strong sense of fair play and always try to find the most equitable solution to arguments.", 
    "I'm confident in my own abilities and do what I can to instill confidence in others.", 
    "Thinking is for other people. I prefer action.", 
    "I misuse long words in an attempt to sound smarter.", 
    "I get bored easily. When am I going to get on with my destiny.", 
    "I believe that everything worth doing is worth doing right. I can't help it--I'm a perfectionist.", 
    "I'm a snob who looks down on those who can't appreciate fine art.", 
    "I always want to know how things work and what makes people tick.", 
    "I'm full of witty aphorisms and have a proverb for every occasion.", 
    "I'm rude to people who lack my commitment to hard work and fair play.", 
    "I like to talk at length about my profession.", 
    "I don't part with my money easily and will haggle tirelessly to get the best deal possible.", 
    "I'm well known for my work, and I want to make sure everyone appreciates it. I'm always taken aback when people haven't heard of me.", 
    "I've been isolated for so long that I rarely speak, preferring gestures and the occasional grunt.", 
    "I am utterly serene, even in the face of disaster.", 
    "The leader of my community has something wise to say on every topic, and I am eager to share that wisdom.", 
    "I feel tremendous empathy for all who suffer.", 
    "I'm oblivious to etiquette and social expectations.", 
    "I connect everything that happens to me to a grand cosmic plan.", 
    "I often get lost in my own thoughts and contemplations, becoming oblivious to my surroundings.", 
    "I am working on a grand philosophical theory and love sharing my ideas.", 
    "My eloquent flattery makes everyone I talk to feel like the most wonderful and important person in the world.", 
    "The common folk love me for my kindness and generosity.", 
    "No one could doubt by looking at my regal bearing that I am a cut above the unwashed masses.", 
    "I take great pains to always look my best and follow the latest fashions.", 
    "I don't like to get my hands dirty, and I won't be caught dead in unsuitable accommodations.", 
    "Despite my birth, I do not place myself above other folk. We all have the same blood.", 
    "My favor, once lost, is lost forever.", 
    "If you do me an injury, I will crush you, ruin your name, and salt your fields.", 
    "I'm driven by a wanderlust that led me away from home.", 
    "I watch over my friends as if they were a litter of newborn pups.", 
    "I once ran twenty-five miles without stopping to warn my clan of an approaching orc horde. I'd do it again if I had to.", 
    "I have a lesson for every situation, drawn from observing nature.", 
    "I place no stock in wealthy or well-mannered folk. Money and manners won't save you from a hungry owlbear.", 
    "I'm always picking things up, absently fiddling with them, and sometimes accidentally breaking them.", 
    "I feel far more comfortable around animals than people.", 
    "I was, in fact, raised by wolves.", 
    "I use polysyllabic words to convey the impression of great erudition.", 
    "I've read every book in the world's greatest libraries--or like to boast that I have.", 
    "I'm used to helping out those who aren't as smart as I am, and I patiently explain anything and everything to others.", 
    "There's nothing I like more than a good mystery.", 
    "I'm willing to listen to every side of an argument before I make my own judgment.", 
    "I...speak...slowly...when talking...to idiots...which...almost...everyone...is...compared...to me.", 
    "I am horribly, horribly awkward in social situations.", 
    "I'm convinced that people are always trying to steal my secrets.", 
    "My friends know they can rely on me, no matter what.", 
    "I work hard so that I can play hard when the work is done.", 
    "I enjoy sailing into new ports and making new friends over a flagon of ale.", 
    "I stretch the truth for the sake of a good story.", 
    "To me, a tavern brawl is a nice way to get to know a new city.", 
    "I never pass up a friendly wager.", 
    "My language is as foul as an otyugh nest.", 
    "I like a job well done, especially if I can convince someone else to do it.", 
    "I'm always polite and respectful.", 
    "I'm haunted by memories of war. I can't get the images of violence out of my mind.", 
    "I've lost too many friends, and I'm slow to make new ones.", 
    "I'm full of inspiring and cautionary tales from my military experience relevant to almost every combat situation.", 
    "I can stare down a hellhound without flinching.", 
    "I enjoy being strong and like breaking things.", 
    "I have a crude sense of humor.", 
    "I face problems head-on. A simple direct solution is the best path to success.", 
    "I hide scraps of food and trinkets away in my pockets.", 
    "I ask a lot of questions.", 
    "I like to squeeze into small places where no one else can get to me.", 
    "I sleep with my back to a wall or tree, with everything I own wrapped in a bundle in my arms.", 
    "I eat like a pig and have bad manners.", 
    "I think anyone who's nice to me is hiding evil intent.", 
    "I don't like to bathe.", 
    "I bluntly say what other people are hinting or hiding."
]
ideals = {
    "Lawful": [
        "Faith. I trust that my deity will guide my actions. I have faith that if I work hard, things will go well.", 
        "Tradition. The ancient traditions of worship and sacrifice must be preserved and upheld.", 
        "Power. I hope to one day rise to the top of my faith's religious hierarchy.", 
        "Fairness. I never target people who can't afford to lose a few coins.", 
        "Honor. I don't steal from others in the trade.", 
        "Tradition. The stories, legends, and songs of the past must never be forgotten.", 
        "Fairness. No one should get preferential treatment before the law, and no one is above the law.", 
        "Community. It is the duty of all civilized people to strengthen the bonds of community and the security of civilization.", 
        "Logic. Emotions must not cloud our sense of what is right and true, or our logical thinking.", 
        "Responsibility. It is my duty to respect the authority of those above me, just as those below me must respect mine.", 
        "Honor. If I dishonor myself, I dishonor my whole clan.", 
        "Logic. Emotions must not cloud our logical thinking.", 
        "Fairness. We all do the work, so we all share in the rewards.", 
        "Responsibility. I do what I must and obey just authority.", 
        "Community. We have to take care of each other, because no one else is going to do it.", 
    ],
    "Chaotic": [
        "Change. We must help bring about the changes the gods are constantly working in the world.", 
        "Independence. I am a free spirit--no one tells me what to do.", 
        "Creativity. I never run the same con twice.", 
        "Freedom. Chains are meant to be broken, as are those who would forge them.", 
        "Creativity. The world is in need of new ideas and bold action.", 
        "Freedom. Tyrants must not be allowed to oppress the people.", 
        "Freedom. Everyone should be free to pursue his or her livelihood.", 
        "Free Thinking. Inquiry and curiosity are the pillars of progress.", 
        "Independence. I must prove that I can handle myself without the coddling of my family.", 
        "Change. Life is like the seasons, in constant change, and we must change with it.", 
        "No Limits. Nothing should fetter the infinite possibility inherent in all existence.", 
        "Freedom. The sea is freedom--the freedom to go anywhere and do anything.", 
        "Independence. When people follow orders blindly they embrace a kind of tyranny.", 
        "Change. The low are lifted up, and the high and mighty are brought down. Change is the nature of things.", 
    ],
    "Good": [
        "Charity. I always try to help those in need, no matter what the personal cost.", 
        "Charity. I distribute money I acquire to the people who really need it.", 
        "Friendship. Material goods come and go. Bonds of friendship last forever.", 
        "Charity. I steal from the wealthy so that I can help people in need.", 
        "Redemption. There's a spark of good in everyone.", 
        "Beauty. When I perform, I make the world better than it was.", 
        "Respect. People deserve to be treated with dignity and respect.", 
        "Generosity. My talents were given to me so that I could use them to benefit the world.", 
        "Greater Good. My gifts are meant to be shared with all, not used for my own benefit.", 
        "Respect. Respect is due to me because of my position, but all people regardless of station deserve to be treated with dignity.", 
        "Noble Obligation. It is my duty to protect and care for the people beneath me.", 
        "Greater Good. It is each person's responsibility to make the most happiness for the whole tribe.", 
        "Beauty. What is beautiful points us beyond itself toward what is true.", 
        "Respect. The thing that keeps a ship together is mutual respect between captain and crew.", 
        "Greater Good. Our lot is to lay down our lives in defense of others.", 
        "Respect. All people, rich or poor, deserve respect.", 
    ],
    "Evil": [
        "Greed. I will do whatever it takes to become wealthy.", 
        "Greed. I'm only in it for the money and fame.", 
        "Might. If I become strong, I can take what I want--what I deserve.", 
        "Greed. I'm only in it for the money.", 
        "Power. Solitude and contemplation are paths toward mystical or magical power.", 
        "Power. If I can attain more power, no one will tell me what to do.", 
        "Might. The strongest are meant to rule.", 
        "Power. Knowledge is the path to power and domination.", 
        "Master. I'm a predator, and the other ships on the sea are my prey.", 
        "Might. In life as in war, the stronger force wins.", 
        "Retribution. The rich need to be shown what life and death are like in the gutters.", 
    ],
    "Neutral": [
        "People. I'm loyal to my friends, not to any ideals, and everyone else can take a trip down the Styx for all I care.", 
        "People. I like seeing the smiles on people's faces when I perform. That's all that matters.", 
        "Sincerity. There's no good pretending to be something I'm not.", 
        "People. I'm committed to the people I care about, not to ideals.", 
        "Live and Let Live. Meddling in the affairs of others only causes trouble.", 
        "Nature. The natural world is more important than all the constructs of civilization.", 
        "Knowledge. The path to power and self-improvement is through knowledge.", 
        "People. I'm committed to my crewmates, not to ideals.", 
        "Ideals aren't worth killing for or going to war for.", 
        "People. I help people who help me--that's what keeps us alive.", 
    ],
    "Any": [
        "Aspiration. I seek to prove my self worthy of my god's favor by matching my actions against his or her teachings.", 
        "Aspiration. I'm determined to make something of myself.", 
        "Honesty. Art should reflect the soul; it should come from within and reveal who we really are.", 
        "Destiny. Nothing and no one can steer me away from my higher calling.", 
        "Aspiration. I work hard to be the best there is at my craft.", 
        "Self-Knowledge. If you know yourself, there're nothing left to know.", 
        "Family. Blood runs thicker than water.", 
        "Glory. I must earn glory in battle, for myself and my clan.", 
        "Self-improvement. The goal of a life of study is the betterment of oneself.", 
        "Aspiration. Someday I'll own my own ship and chart my own destiny.", 
        "Nation. My city, nation, or people are all that matter.", 
        "Aspiration. I'm going to prove that I'm worthy of a better life.", 
    ]
}
bonds = [
    "I would die to recover an ancient artifact of my faith that was lost long ago.",
    "I will someday get revenge on the corrupt temple hierarchy who branded me a heretic.",
    "I owe me life to the priest who took me in when my parents died.",
    "Everything I do is for the common people.",
    "I will do anything to protect the temple where I served.",
    "I seek to preserve a sacred text that my enemies consider heretical and seek to destroy.",
    "I fleeced the wrong person and must work to ensure that this individual never crosses paths with me or those I care about.",
    "I owe everything to my mentor--a horrible person who's probably rotting in jail somewhere.",
    "Somewhere out there I have a child who doesn't know me. I'm making the world better for him or her.",
    "I come from a noble family, and one day I'll reclaim my lands and title from those who stole them from me.",
    "A powerful person killed someone I love. Some day soon, I'll have my revenge.",
    "I swindled and ruined a person who didn't deserve it. I seek to atone for my misdeeds but might never be able to forgive myself.",
    "I'm trying to pay off an old debt I owe to a generous benefactor.",
    "My ill-gotten gains go to support my family.",
    "Something important was taken from me, and I aim to steal it back.",
    "I will become the greatest thief that ever lived.",
    "I'm guilty of a terrible crime. I hope I can redeem myself for it.",
    "Someone I loved died because of a mistake I made. That will never happen again.",
    "My instrument is my most treasured possession, and it reminds me of someone I love.",
    "Someone stole my precious instrument, and someday I'll get it back.",
    "I want to be famous, whatever it takes.",
    "I idolize a hero of the old tales and measure my deeds against that person's.",
    "I will do anything to prove myself superior to me hated rival.", 
    "I would do anything for the other members of my old troupe.", 
    "I have a family, but I have no idea where they are. One day, I hope to see them again.", 
    "I worked the land, I love the land, and I will protect the land.", 
    "A proud noble once gave me a horrible beating, and I will take my revenge on any bully I encounter.", 
    "My tools are symbols of my past life, and I carry them so that I will never forget my roots.", 
    "I protect those who cannot protect themselves.", 
    "I wish my childhood sweetheart had come with me to pursue my destiny.", 
    "The workshop where I learned my trade is the most important place in the world to me.", 
    "I created a great work for someone, and then found them unworthy to receive it. I'm still looking for someone worthy.", 
    "I owe my guild a great debt for forging me into the person I am today.", 
    "I pursue wealth to secure someone's love.", 
    "One day I will return to my guild and prove that I am the greatest artisan of them all.", 
    "I will get revenge on the evil forces that destroyed my place of business and ruined my livelihood.", 
    "Nothing is more important than the other members of my hermitage, order, or association.", 
    "I entered seclusion to hide from the ones who might still be hunting me. I must someday confront them.", 
    "I'm still seeking the enlightenment I pursued in my seclusion, and it still eludes me.", 
    "I entered seclusion because I loved someone I could not have.", 
    "Should my discovery come to light, it could bring ruin to the world.", 
    "My isolation gave me great insight into a great evil that only I can destroy.", 
    "I will face any challenge to win the approval of my family.", 
    "My house's alliance with another noble family must be sustained at all costs.", 
    "Nothing is more important that the other members of my family.", 
    "I am in love with the heir of a family that my family despises.", 
    "My loyalty to my sovereign is unwavering.", 
    "The common folk must see me as a hero of the people.", 
    "My family, clan, or tribe is the most important thing in my life, even when they are far from me.", 
    "An injury to the unspoiled wilderness of my home is an injury to me.", 
    "I will bring terrible wrath down on the evildoers who destroyed my homeland.", 
    "I am the last of my tribe, and it is up to me to ensure their names enter legend.", 
    "I suffer awful visions of a coming disaster and will do anything to prevent it.", 
    "It is my duty to provide children to sustain my tribe.", 
    "It is my duty to protect my students.", 
    "I have an ancient text that holds terrible secrets that must not fall into the wrong hands.", 
    "I work to preserve a library, university, scriptorium, or monastery.", 
    "My life's work is a series of tomes related to a specific field of lore.", 
    "I've been searching my whole life for the answer to a certain question.", 
    "I sold my soul for knowledge. I hope to do great deeds and win it back.", 
    "I'm loyal to my captain first, everything else second.", 
    "The ship is most important--crewmates and captains come and go.", 
    "I'll always remember my first ship.", 
    "In a harbor town, I have a paramour whose eyes nearly stole me from the sea.", 
    "I was cheated of my fair share of the profits, and I want to get my due.", 
    "Ruthless pirates murdered my captain and crewmates, plundered our ship, and left me to die. Vengeance will be mine.", 
    "I would lay down my life for the people I served with.", 
    "Someone saved my life on the battlefield. To this day, I will never leave a friend behind.", 
    "My honor is my life.", 
    "I'll never forget the crushing defeat my company suffered or the enemies who dealt it.", 
    "Those who fight beside me are those worth dying for.", 
    "I fight for those who cannot fight for themselves.", 
    "My town or city is my home, and I'll fight to defend it.", 
    "I sponsor an orphanage to keep others from enduring what I was forced to endure.", 
    "I owe my survival to another urchin who taught me to live on the streets.", 
    "I owe a debt I can never repay to the person who took pity on me.", 
    "I escaped my life of poverty by robbing an important person, and I'm wanted for it.", 
    "No one else is going to have to endure the hardships I've been through."
    ]
flaws = [
    "I judge others harshly, and myself even more severely.", 
    "I put too much trust in those who wield power within my temple's hierarchy.", 
    "My piety sometimes leads me to blindly trust those that profess faith in my god.", 
    "I am inflexible in my thinking.", 
    "I am suspicious of strangers and suspect the worst of them.", 
    "Once I pick a goal, I become obsessed with it to the detriment of everything else in my life.", 
    "I can't resist a pretty face.", 
    "I'm always in debt. I spend my ill-gotten gains on decadent luxuries faster than I bring them in.", 
    "I'm convinced that no one could ever fool me in the way I fool others.", 
    "I'm too greedy for my own good. I can't resist taking a risk if there's money involved.", 
    "I can't resist swindling people who are more powerful than me.", 
    "I hate to admit it and will hate myself for it, but I'll run and preserve my own hide if the going gets tough.", 
    "When I see something valuable, I can't think about anything but how to steal it.", 
    "When faced with a choice between money and my friends, I usually choose the money.", 
    "If there's a plan, I'll forget it. If I don't forget it, I'll ignore it.", 
    "I have a 'tell' that reveals when I'm lying.", 
    "I turn tail and run when things go bad.", 
    "An innocent person is in prison for a crime that I committed. I'm okay with that.", 
    "I'll do anything to win fame and renown.", 
    "I'm a sucker for a pretty face.", 
    "A scandal prevents me from ever going home again. That kind of trouble seems to follow me around.", 
    "I once satirized a noble who still wants my head. It was a mistake that I will likely repeat.", 
    "I have trouble keeping my true feelings hidden. My sharp tongue lands me in trouble.", 
    "Despite my best efforts, I am unreliable to my friends.", 
    "The tyrant who rules my land will stop at nothing to see me killed.", 
    "I'm convinced of the significance of my destiny, and blind to my shortcomings and the risk of failure.", 
    "The people who knew me when I was young know my shameful secret, so I can never go home again.", 
    "I have a weakness for the vices of the city, especially hard drink.", 
    "Secretly, I believe that things would be better if I were a tyrant lording over the land.", 
    "I have trouble trusting in my allies.", 
    "I'll do anything to get my hands on something rare or priceless.", 
    "I'm quick to assume that someone is trying to cheat me.", 
    "No one must ever learn that I once stole money from guild coffers.", 
    "I'm never satisfied with what I have--I always want more.", 
    "I would kill to acquire a noble title.", 
    "I'm horribly jealous of anyone who outshines my handiwork. Everywhere I go, I'm surrounded by rivals.", 
    "Now that I've returned to the world, I enjoy its delights a little too much.", 
    "I harbor dark bloodthirsty thoughts that my isolation failed to quell.", 
    "I am dogmatic in my thoughts and philosophy.", 
    "I let my need to win arguments overshadow friendships and harmony.", 
    "I'd risk too much to uncover a lost bit of knowledge.", 
    "I like keeping secrets and won't share them with anyone.", 
    "I secretly believe that everyone is beneath me.", 
    "I hide a truly scandalous secret that could ruin my family forever.", 
    "I too often hear veiled insults and threats in every word addressed to me, and I'm quick to anger.", 
    "I have an insatiable desire for carnal pleasures.", 
    "In fact, the world does revolve around me.", 
    "By my words and actions, I often bring shame to my family.", 
    "I am too enamored of ale, wine, and other intoxicants.", 
    "There's no room for caution in a life lived to the fullest.", 
    "I remember every insult I've received and nurse a silent resentment toward anyone who's ever wronged me.", 
    "I am slow to trust members of other races", 
    "Violence is my answer to almost any challenge.", 
    "Don't expect me to save those who can't save themselves. It is nature's way that the strong thrive and the weak perish.", 
    "I am easily distracted by the promise of information.", 
    "Most people scream and run when they see a demon. I stop and take notes on its anatomy.", 
    "Unlocking an ancient mystery is worth the price of a civilization.", 
    "I overlook obvious solutions in favor of complicated ones.", 
    "I speak without really thinking through my words, invariably insulting others.", 
    "I can't keep a secret to save my life, or anyone else's.", 
    "I follow orders, even if I think they're wrong.", 
    "I'll say anything to avoid having to do extra work.", 
    "Once someone questions my courage, I never back down no matter how dangerous the situation.", 
    "Once I start drinking, it's hard for me to stop.", 
    "I can't help but pocket loose coins and other trinkets I come across.", 
    "My pride will probably lead to my destruction", 
    "The monstrous enemy we faced in battle still leaves me quivering with fear.", 
    "I have little respect for anyone who is not a proven warrior.", 
    "I made a terrible mistake in battle that cost many lives--and I would do anything to keep that mistake secret.", 
    "My hatred of my enemies is blind and unreasoning.", 
    "I obey the law, even if the law causes misery.", 
    "I'd rather eat my armor than admit when I'm wrong.", 
    "If I'm outnumbered, I always run away from a fight.", 
    "Gold seems like a lot of money to me, and I'll do just about anything for more of it.", 
    "I will never fully trust anyone other than myself.", 
    "I'd rather kill someone in their sleep than fight fair.", 
    "It's not stealing if I need it more than someone else.", 
    "People who don't take care of themselves get what they deserve."
]
# END posted on reddit by u/RamonDozol

motivations = {
    # START posted by Darcy Pattison on her website
    "https://www.darcypattison.com/writing/revision/villain-motivations/": [
        "Romance: I want to marry the princess.", 
        "Revenge - ruin a hero: I want to ruin the King.", 
        "To distinguish oneself: I want the princess to respect me.", 
        "To fit in/gain acceptance: I want to attend the princess' coronation and eat at her table.", 
        "Justice: The king killed my mother, so the king must die.", 
        "Greed - get rich: I want to steal everything from the King's treasury.", 
        "Fear: I am afraid that our lands will be stripped bare by this evil king.", 
        "Desperation: If something doesn't change in the next week, I will be executed.", 
        "Social cohesion: Us zombies need to stick together.", 
        "Desire to better oneself: I was born a peasant, but I will die a king.", 
        "Power to achieve a goal: I must be king, so I can change the laws about owning property.", 
        "Escape destiny: At birth, a prophet said I would kill the king; however, I am stealing enough money to escape to another country and avoid that destiny.", 
        "Achieve destiny: At birth, a prophet said I would kill the king; and that's my plan.", 
        "Persecution: Growing up in a wheelchair has been hell.", 
        "Rivalry: Prince John wants to marry the Princess, but she's mine.", 
        "Discovery: I will find out the king's darkest secret and use it against him.", 
        "Ambition: I want. . . everything!", 
        "Survival (deliverance): In the midst of this civil war, I will survive.", 
        "Self-sacrifice: Someone must stop this evil king and I've decided to step up and do it.", 
        "Love: The princess has stolen my heart; so, I'll steal her.", 
        "Hate: The princess is an evil woman; when she becomes my wife, I'll make her suffer.", 
        "Conspiracy: I've gathered twelve good men to help me overthrow this king.", 
        "Honor: Men from my city never back down, even if it costs me everything.", 
        "Dishonor: Men from my city are idiots; I'll never do things the “right” way.", 
        "Unnatural affection: I want to marry the princess and take the queen as a lover.", 
        "Catastrophe: A volcano is going to erupt and when it does, I'll plunder the city.", 
        "Grief and loss: When my mother died, I lost all interest in doing good.", 
        "Rebellion: I'm the leader of the guerrilla forces.", 
        "Betrayal: I was engaged to the princess, and then she married Prince John.", 
        "Spread hate and fear: I love hate. Hate, hate, hate.", 
        "Corrupt everyone: Come join me as I rob the king.", 
        "Control the kids: If those kids make noise one more time at midnight, I'll get 'em.", 
        "Leave me in peace: I never wanted to leave my home town, but since you've made me, I'll show you what's what.", 
        "Recover what is lost: The king took my mother's locket as tribute, and if it's the last thing I ever do, I'll get it back.", 
        "Save humanity: To save humanity, I'll have to kill the whole army.", 
        "serve a master (ex. The Fuhrer): I'll follow King George anywhere, even if it means killing King Phillip.", 
        "Destroy: Ha! Ha! Ha! I love to burn down houses.", 
        "Rule part of the world: I want to be King of the Mermaids.", 
        "Rule all of the world: I will rule the Earth."
    ],
    # END posted by Darcy Pattison on her website

    # START posted on reddit by u/lumenwrites
    "https://www.reddit.com/r/d100/comments/hsxbz9/lists_of_100_villains_evil_organizations_evil/": [
        "Pride/Ego (Prove themselves to someone).", 
        "Greed (Gain Wealth).", 
        "Envy (Destroy their rival).", 
        "Political Power (Rule an organization/town/kingdom/world).", 
        "Magic Power.", 
        "Knowledge.", 
        "Gain Fame, Respect, Influence, Social Status.", 
        "Revenge (kill/hurt a person/people who harmed them or someone they loved).", 
        "Fear (Do whatever it takes to survive.)", 
        "Misguided sense of Justice", 
        "Hatred (of a person/group/class/race).", 
        "Love/Lust (Seduce a princess).", 
        "Amusement/Entertainment (hurt people for fun).", 
        "Cruelty, dark/violent urges.", 
        "Biological necessity (drink blood, eat people, rampage).", 
        "Following orders.", 
        "Competitive spirit, desire to win.", 
        "Fanatical Patriotism.", 
        "Freedom/liberty (escape their imprisonment/curse to roam free in the world again).", 
        "Eternal youth, immortality.", 
        "Resurrect their loved one.", 
        "Repay their debt to the devil.", 
        "Escape pursuit of the law.", 
        "Faith/Religion. (Resurrect an ancient evil or a god, make sacrifices to the higher power.)", 
        "Ensure the success of their business/organization by any means.", 
        "Spread chaos and mess with people.", 
        "Enforce the status quo / unjust laws.", 
        "Enforce the will of their gods.", 
        "Conquest. Conquer/enslave region.", 
        "Defeat their enemy.", 
        "Regain their honor (by committing deeds their father/family/clan will find 'worthy').", 
        "Get summoned/resurrected (escape from hell, get their servants to commit the ritual that will birth them into the world).", 
        "Complete some world altering task before their death.", 
        "Maintain the power/status they already possess.", 
        "Obsessive pursuit of a goal, anyone or anything that gets destroyed along the way is just collateral damage.", 
        "Resurrect their child/god/leader/master/teacher.", 
        "To cleanse the world of the inferior, non-believers, unworthy, etc.", 
        "To harden the people in preparation for some catastrophic event (real, imagined, prophesied) that is approaching.", 
        "Infamy. They seek to out do all other villains (past or present)."
    ],
    # END posted on reddit by u/lumenwrites
    "": [],
}

villains = [
    [
    # START posted on reddit by u/lumenwrites
        "Assassin", 
        "Bounty Hunter", 
        "Criminal", 
        "Corrupt official", 
        "Crazy Scientist/Alchemist/Mage", 
        "Evil Wizard", 
        "Necromancer/lich", 
        "Religious Leader", 
        "Deadly Monster/Creature", 
        "Witch", 
        "Demon", 
        "Evil Machiavellian Mastermind", 
        "Your own employer", 
        "Your old mentor", 
        "Oppressive ruler", 
        "Brilliant Detective", 
        "Blackmailer", 
        "Military officer/general", 
        "Serial Killer", 
        "Noble/Lord", 
        "Misguided Former Hero", 
        "Organized Crime Boss", 
        "Powerful Businessman/Merchant", 
        "Fugitive/Criminal", 
        "Shaman", 
        "Trickster", 
        "Acolyte of a (dark god, demon, devil, old one, outsider)", 
        "Advisor to the (emperor, king, sultan, etc)", 
        "Alien Invader from another (dimension, plane of existence, world)", 
        "Alternate (dimension, history) version of hero", 
        "Being that has been imprisoned or in stasis for 100s to 1000s of years", 
        "Construct (body possessed by the villain, experiment of a mad mage or scientist, weapon from a bygone age)", 
        "Corrupted angel, hero, or priest / The Fallen", 
        "Demigod", 
        "Former teammate that everyone thought was dead", 
        "Next in line to be ruler", 
        "Possessed Hero or Priest"
    # END posted on reddit by u/lumenwrites
    ],

],

organizations = [
    # START posted on reddit by u/lumenwrites
    "Powerful Organization (business, guild, etc)", 
    "Secret Society/Conspiracy", 
    "Cultists", 
    "Religious Fanatics", 
    "Foreign Nation", 
    "Thieves Guild", 
    "Gangs/Thugs", 
    "Spies, secret government agents.", 
    "Brainwashed/insane/mind-controlled group.", 
    "Hired muscle, mercenaries.", 
    "Misguided/evil locals", 
    "Angry Mob", 
    "Kidnappers/Slavers", 
    "Rebels", 
    "Terrorists", 
    "Mutants/outcasts", 
    "Witch-hunters", 
    "Invaders", 
    "Rival group of adventurers", 
    "Tribe/horde of orcs/goblins/kobolds/etc", 
    "Infestation", 
    "Spirits/Ghosts", 
    "Zombies", 
    "Vampires", 
    "Pirates", 
    "Ninjas"
    # END posted on reddit by u/lumenwrites
]

# START posted by Harry on https://blackcitadelrpg.com/group-patrons-5e/
patrons = {
    "Academy": [
        "Aberrant Zoology. You undertake expeditions to document, capture, and explain beings antithetical to the natural order.", 
        "Arcanodynamics. You investigate the ways magic underpins existence, exploring its flows and seeking ways to harness its nexuses.", 
        "Forbidden History. You reveal the lost truths of the world's darkest ages, pursuing the history of purposefully hidden or taboo eras.", 
        "Cryptogeography. You search for proof of a hidden land or that the world isn't structured as commonly assumed.", 
        "Restorative Antiquarianism. You track clues leading to plundered artifacts and then restore them to their rightful owners.", 
        "Evolutionary Divinity. You dare to explore what no mortal was meant to know: the origins of divinity.", 
    ],
    "Ancient Being": [
        "Elder Dragon. An ancient dragon seeks knowledge or power. It wishes to gather greater wealth for its hoard, its ambitions expanding in its advancing years.", 
        "Lich. An undead spellcaster of immense power employs your group. Its interests are strangely diverse and seemingly benign. Perhaps it's not as evil as conventional adventuring wisdom suggests?", 
        "Bound Fiend. This fiend is bound to a location, either in its true form or as a possessing spirit. Whether trapped in an unbreakable circle of binding sigils or sealed as a spirit within a gigantic statue, the fiend's influence drives your group.", 
        "Guardian Celestial. An angel or another powerful celestial takes an interest in a specific region of the Material Plane. It cultivates a network of mortal informants and agents to serve its agenda.", 
        "The Endless. This person has lived many lifetimes because they can't die—at least not permanently. No matter the cause of their demise, they return. To all appearances, they are alive and mortal, but they control the amassed resources of an immortal.", 
        "Primal Manifestation. Its existence defies mortal understanding; the being simply is. It could be a primordial force of nature awakened to self-awareness that now inhabits the landscape or an alien intellect that whispers through proxies, omens, and idols."
    ],
    "Aristocrat": [
        "Local Lord. Convinced that power and prestige lie just around the corner, this minor lordling grasps for every opportunity to climb the ranks.", 
        "Merchant Mastermind. Reputation, wealth, and power are one and the same for the head of a family with world-spanning business holdings.", 
        "Nomadic Princeling. Nothing is more appealing to this princeling than treasure. Their sprawling merchant caravan trails behind their palanquin as far as the eye can see.", 
        "Double Dealer. The leader of a noble family has turned against their nation, secretly opposing their liege for personal gain or ethical reasons.", 
        "Ambitious Entrepreneur. The sole heir of a vast fortune, this entrepreneur seeks allies to expand their wealth in a new business on the international, global, or planar stage.", 
        "Future Ruler. This young noble is destined to rule, but currently their whims are fickle and dangerous."
    ],
    "Criminal Syndicate": [
        "Thieves' Guild. A disparate convocation of thieves, spies, smugglers, and other scoundrels controls criminal activity in a region of a city.", 
        "Assassin Society. The network's livelihood is death. Members of the society hone their skills as cutthroats, poisoners, body-disposal specialists, and any other profession focused on ending lives. The society is motivated by profit or labors in service to a greater cause.", 
        "Magical Arms Dealer. The syndicate has cornered the market on deadly magical devices. They offer their services and wares for a price and acquire staggering magical might for those who meet their demands.", 
        "Pirate Fleet. This alliance of pirate captains is unified under a ruling captain or admiral and adheres to a strict code of honor. They converge only in response to an outside threat.", 
        "Body Snatchers. The syndicate consists predominantly, if not entirely, of creatures that possess or impersonate other people. They seek to replace influential individuals throughout society with members of their ranks.", 
        "Thought Thieves. These psychic criminals infiltrate their target's minds to steal secrets and disguise their existence."
    ],
    "Guild": [
        "Crafters' Guild. This conglomerate of artisans pools its resources and influence to ensure a steady exchange of gold for its crafts.", 
        "Merchant Consortium. These entrepreneurs don't create the wares they peddle, instead specializing in linking products to prospective owners. If they don't have it, they find it.", 
        "Miracle Makers' Association. The magically inclined crafters of this guild specialize in imbuing physical goods with magical effects. Rumor has it they can strip the magic from existing enchanted items and might be willing to buy or trade adventurers' spoils.", 
        "Moneychangers. These merchants deal in all forms of currency, acting as bankers, loan agents, and crucial contacts for adventurers and other individuals who deal with large sums of wealth. They exchange coins for gemstones as readily as they find buyers for historical relics and recovered art.", 
        "Philosophical Faction. These like-minded individuals follow specific teachings, spreading word of their expertise through their services and training.", 
        "Identity Traders. These enigmatic dealers buy and sell documents, memories, and the trappings of thoroughly lived lives, selling them to those in need of the ultimate fresh start."
    ],
    "Military Force": [
        "Standing Army. A standing army serves as the highly disciplined and structured guardian of a province or an entire nation. Strict tiers of command ensure coordination between branches of the force.", 
        "Mercenary Company. Hard-bitten veterans of numerous conflicts, mercenaries serve an employer for coin rather than out of loyalty.", 
        "Expeditionary Force. This military force is far from home, fighting behind enemy lines or striking into wild, unsettled lands. The force must be fast, self-sufficient, and either diplomatic or decisive to assure their survival.", 
        "Horde. The horde is almost a force of nature, and what it lacks in discipline it makes up in ferocity. It doesn't have a rigid command structure, instead functioning like a pyramid of smaller armies. Horde commanders owe fealty to stronger leaders above them, all the way up to the warlord.", 
        "Planar Conscripts. This military force battles for cosmic stakes on far-flung planes of the multiverse or fights against extraplanar invasion on the Material Plane. Warriors include conscripts pressed into service in the Blood War, fodder in the thrall of ruthless yugoloth mercenaries, or members of a glorious celestial host defending against fiendish incursion.", 
        "Sky Warriors. This military force consists of winged creatures, employs magical flight, or sails airships as a sky navy. Traditional defenses are ineffective against attacks from the air, positioning the sky warriors as a fearsome nation or expensive and coveted mercenaries."
    ],
    "Religious Order": [
        "Undead Hunters. This community of scholars and monster hunters laboriously researches the unquiet dead, tracking them to their lairs and permanently laying them to rest.", 
        "Devout Scholars. This federation prizes knowledge and texts pertaining to their god. They collect rare holy books and record the life stories of miracle-working prophets.", 
        "Relic Collectors. This order of archeologist-monks seeks to fill their museum-like temple with storied holy relics.", 
        "Charitable Missionaries. Adhering to the belief that religion empowers civilization, this order travels far to help the downtrodden, seeking to draw new believers by their virtuous example.", 
        "Militant Inquisitors. This dogmatically rigid hierarchy seeks to stamp out all threats to their beliefs.", 
        "Doomsaying Evangelists. This order believes the world is about to end. They're convinced that if they persuade everyone else of this fact, they might stave off the impending doom."
    ],
    "Sovereign": [],
    "": [],
    "": [],

}
# END posted by Harry on https://blackcitadelrpg.com/group-patrons-5e/

# START sourced from https://creativerogues.tumblr.com/post/631529713014374400/1d20-dark-secrets-your-dd-character-would-prefer
secrets = [
    "I have a Child I didn't raise.", 
    "I disposed of a Dagger that may have been evidence in a Murder.", 
    "I once sold out a friend for 100 Gold Pieces.", 
    "I have a mysterious illness I keep hidden from sight.", 
    "I'm addicted to Potions of all magical varieties.", 
    "I put my trust and faith in a Deity that is overtly evil.", 
    "I am writing a biography of my life, but embellishing it to make myself sound more heroic.", 
    "I'm technically not alive.", 
    "I lost several minor appendages due a gambling addition fuelled by a local moneylending gang.", 
    "I've been exiled twice under different names.", 
    "I'm nothing but a construct made from the flesh of a (in)famous local noble.", 
    "I was forced to watch my family's execution.", 
    "I'm the reincarnation of a legendary warrior, I swear!", 
    "I am the only surviving member of my previous adventuring party.", 
    "I have an irrational fear of cats.", 
    "I carry the skull of my best friend.", 
    "I hate the monarchy.", 
    "I fear that the Party will try to kill me if I leave or speak out of turn.", 
    "I was once imprisoned for my religious beliefs, but escaped under the cover of darkness.", 
    "I was raised as a hostage of my family's enemies after my parents refused to pay the ransom.", 
    "Never meant to be: I was rejected by a lover, one I thought truly loved me back.", 
    "Scorned by the Gods: The Gods have turned their back on the Mortal Realms and still cast shame upon those who fall to war and disease in their absence. I do not voice it openly, but this does not seem fair nor just.", 
    "Once a Criminal: I've engaged in theft before, I've even been caught. It was a low moment, but I'm bitter to how it colours my character.", 
    "Differing Thoughts: I was condemned by my order and masters in the past for daring to speak so openly on topics they deeply disagree with.", 
    "So Scandalous!: I was once part of a scandal within a noble city, the sort that follows a person and causes mockery when it does not cause death.", 
    "Luxurious Living: I dwelled for a time in hedonism and luxury, allowing good folk to die in my stead.", 
    "Stolen Alias: I steal valour from the dead.", 
    "Cursed!: I suffered from a terrible curse for many years, it ravaged my mind and ran ragged on my soul. I was freed only recently, and I fear what darkness I may have indulged in while under it.", 
    "The Replacement: I was replaced. I had been gone for a moment, recovering or just away like anyone should be allowed to be. I returned and I was replaced, so easily. They lavished praise upon my replacement, they claimed them better than I ever was. I fear my companions may do the same with me.", 
    "Twisted Mercy: I think the worst part about the tribesmen I fought was that they did not kill me. One grabbed me by the throat and screamed I wasn't fighting properly, that I wasn't giving it my all. That they knew I had a purpose, a power, and that if I wasn't going to fight to their joy, I may as well leave. To be given “mercy” by such wild peoples, I cannot stand for that mark on my honour."
]
fears = [
    "True Love. I fear true love, of being in the presence of a purity of emotional honesty that I will never know.", 
    "Famine. I have seen those who die by starvation, a death of indignity. I know how easily I too could suffer such a fate. It puts a sick feeling in my gut, one that is not easily remedied.", 
    "Deep Water. I fear the dark abyss of the Sea, the uncertainty of what lurks in those endless depths, and the writhing creatures beneath the waves that may seek to steal my soul.", 
    "The Wilderness. I fear the dark of the woods, for I have learned and made known of what dark things dwell within such places.", 
    "Cowardice. I fear being revealed a coward, that in some act of horror I will do what it is only natural and be forever shamed.", 
    "The Afterlife. I fear that upon my demise, however good or righteous it might be, that I will still be cast into the cruel and cold hands of an eternally alone and dark afterlife.", 
    "Loss of Control. I fear loss of my self, loss of my being; my face, my ego. I worked so hard to be notably myself, and to have this marred and invalidated, to look upon myself and not see me…that terrifies me deeply.", 
    "Undeath. I've witnessed the terrors of undeath, of spectres and skeletons, and so I fear my corpse may not stay motionless forever…"
]
life_events = [
    "The love of your young life died in your arms during a raider attack.", 
    "You bravely fought off several bandits as a young teenager.", 
    "You went into a series of ancient ruins on a dare and almost died — a family member or loved one saved you.", 
    "You went on a hunt with your village and landed the killing blow on a great beast.", 
    "While resting under a tree, a spirit appeared and talked to you.", 
    "Your village was ransacked by a group of strangers and most of the villagers were taken.", 
    "The Local Nobility took everything you had as “Tax”.", 
    "You used your powers to bully those in your village; eventually they rose up against you and you were exiled.", 
    "You came across a demon in your youth and battled it in a test of wills. Somehow you survived, but at what cost?", 
    "You were a loner and shunned in your village. Only a friendly ally stood by your side and eventually died defending your honour.", 
    "You have used your powers many times to protect your fellow villagers. The village considers you a hero.", 
    "You unknowingly entered the borders of a mysterious country or realm. Their peoples immediately arrested you.", 
    "You battled another great and powerful creature in your youth and won, but part of their consciousness somehow lingers within you.", 
    "Your family abandoned you in the wastes and local timberlands, but somehow you survived.", 
    "As a child you lost your temper and “accidentally” set fire to several of the houses in the village.", 
    "You travelled with a Ruin-Robber for a few years. The two of you discovered many interesting ancient ruins and trinkets during your travels.", 
    "Your seven sisters and five brothers were transformed into statues by a powerful mage after you angered them.", 
    "One of your loved ones was a brilliant mind and wrote any helpful stupendous articles and tomes on magic. Eventually they wronged a powerful mage and was killed in front of you.", 
    "You messed with one of your people's priceless artefacts and broke it. You have been exiled by your people for your crimes.", 
    "You joined an order of worshippers who believed they had a higher and more powerful calling. You found them far too extreme and have since left, however they still desire you to return to their fold.", 
    "You became possessed by a vile spirit and killed several innocent people. You have been attempting to atone ever since.", 
    "You used your powers to pull the life force out of a group of rampaging raiders. Even though you saved your fellow townsfolk, they are deathly afraid of you.", 
    "For a brief time you ruled over a small village of people, before being pushed out by a another.", 
    "You were forced by an influential person to use your powers to cause much harm to many people.", 
    "By using calm judgment and consulting with the spirits you were able to quell a feud between families that had been going on for generations.", 
    "You fell in a crevice and nearly died!", 
    "You became lost in your environment and called out for aid. A spirit heard your pleas and guided you out. Sometimes the spirit still comes to visit you.", 
    "After falling into a mud puddle, you slept for centuries. You killed the person that woke you and hid their body.", 
    "You fought off kidnappers who were attempting to take your loved ones.", 
    "While on a hunt you came across the lair of a dragon. It emerged, talked to you, and let you leave.", 
    "You won a championship fighting contest in your youth and are considered a celebrity in your tribe.", 
    "You were chased out of your village after causing too much trouble with your childish pranks.", 
    "You were imprisoned for a crime you didn't commit."
]
# END sourced from https://creativerogues.tumblr.com/post/631529713014374400/1d20-dark-secrets-your-dd-character-would-prefer

# 5e tools pull monster data in conjunction with Kobold+
# for example: https://5e.tools/bestiary.html#adult%20amethyst%20dragon_ftd
