# Generated by Django 4.1 on 2022-09-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_OSOS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default=None, upload_to='images/')),
                ('size', models.CharField(blank=True, max_length=16, null=True)),
                ('portfolio', models.ManyToManyField(blank=True, related_name='maps', to='app_OSOS.portfolio')),
            ],
        ),
    ]
