# Generated by Django 4.1 on 2022-09-15 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Villain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('clan_name', models.CharField(blank=True, max_length=255, null=True)),
                ('race', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(max_length=255)),
                ('villain_type', models.CharField(blank=True, max_length=255, null=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('motivation', models.TextField(blank=True, null=True)),
                ('secret', models.TextField(blank=True, null=True)),
                ('fear', models.TextField(blank=True, null=True)),
                ('life_event', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
