# Generated by Django 4.1 on 2022-09-17 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_OSOS', '0001_initial'),
        ('app_setting_generator', '0002_villain_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='villain',
            name='portfolio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='villains', to='app_OSOS.portfolio'),
        ),
    ]
