# Generated by Django 4.1 on 2022-09-09 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_OSOS', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('alignment', models.CharField(blank=True, max_length=255, null=True)),
                ('ac', models.CharField(blank=True, max_length=255, null=True)),
                ('hp', models.CharField(blank=True, max_length=255, null=True)),
                ('speed', models.CharField(blank=True, max_length=255, null=True)),
                ('strength', models.CharField(blank=True, max_length=255, null=True)),
                ('dexterity', models.CharField(blank=True, max_length=255, null=True)),
                ('constitution', models.CharField(blank=True, max_length=255, null=True)),
                ('intelligence', models.CharField(blank=True, max_length=255, null=True)),
                ('wisdom', models.CharField(blank=True, max_length=255, null=True)),
                ('charisma', models.CharField(blank=True, max_length=255, null=True)),
                ('saving_throws', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('damage_vulnerabilities', models.TextField(blank=True, null=True)),
                ('damage_resistances', models.TextField(blank=True, null=True)),
                ('damage_immunities', models.TextField(blank=True, null=True)),
                ('condition_immunities', models.TextField(blank=True, null=True)),
                ('senses', models.TextField(blank=True, null=True)),
                ('languages', models.TextField(blank=True, null=True)),
                ('cr', models.TextField(blank=True, null=True)),
                ('traits', models.TextField(blank=True, null=True)),
                ('actions', models.TextField(blank=True, null=True)),
                ('bonus_actions', models.TextField(blank=True, null=True)),
                ('reactions', models.TextField(blank=True, null=True)),
                ('legendary_action', models.TextField(blank=True, null=True)),
                ('mythic_actions', models.TextField(blank=True, null=True)),
                ('lair_actions', models.TextField(blank=True, null=True)),
                ('regional_effects', models.TextField(blank=True, null=True)),
                ('environment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monsters', models.TextField(blank=True, null=True)),
                ('party', models.CharField(blank=True, max_length=255, null=True)),
                ('exp', models.CharField(blank=True, max_length=16, null=True)),
                ('adjusted_exp', models.CharField(blank=True, max_length=16, null=True)),
                ('difficulty', models.CharField(blank=True, max_length=16, null=True)),
                ('portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='portfolios', to='app_OSOS.portfolio')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
