# Generated by Django 4.1 on 2022-09-05 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_encounter_builder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monster',
            name='challenge_rating',
        ),
        migrations.AddField(
            model_name='encounter',
            name='adjusted_exp',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='exp',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='party',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='ac',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='actions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='alignment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='bonus_actions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='charisma',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='condition_immunities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='constitution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='cr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='damage_immunities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='damage_resistances',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='damage_vulnerabilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='dexterity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='environment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='hp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='intelligence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='lair_actions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='languages',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='legendary_action',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='mythic_actions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='reactions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='regional_effects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='saving_throws',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='senses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='speed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='strength',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='traits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='wisdom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='monsters',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
