# Generated by Django 4.1 on 2022-09-19 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_OSOS', '0001_initial'),
        ('app_encounter_builder', '0002_alter_encounter_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='app_OSOS.portfolio'),
        ),
    ]
