# Generated by Django 4.1 on 2022-09-07 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_encounter_builder', '0002_remove_monster_challenge_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='difficulty',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
