# Generated by Django 4.1 on 2022-09-08 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_OSOS', '0002_remove_portfolio_encounters'),
        ('app_encounter_builder', '0003_encounter_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='portfolios', to='app_OSOS.portfolio'),
        ),
    ]
